### ISSUE TITLE
[BUG] Odin Does not spawn into world properly

### ISSUE THREAD

**Issue by sbtoonz** [sbtoonz/buzzvalheimmods#4]
On existing world join Odin does not spawn properly at spawn loc

you must use /odinhere in chat to make him instantiate

**Comment by Digitalroot** [comment]
From what I can tell this in intended. After using /odinhere use /setodin to save the location for next time. Doing this works for me. 

/odinhere "Summons Odin to your Current Location"
/setodin "Sets Odin's Position in the config, when rejoining a server Odin should spawn in this location."

**Comment by sbtoonz** [comment]
Odin used to auto spawn on local join at WorldSpawn so this was notated expecting that behavior
